### ISSUE TITLE
TableViewer scrollable issue

### ISSUE THREAD

**Issue by apixandru** [xwic/jWic#28]
If you don't set the width on a table column the table viewer displays just fine as long as it isn't scrollable. When it's scrollable the column width is set to 0.

**Comment by lippisch** [comment]
Hmmmmm.... If scrolling is disabled, it renders a regular table with no width set so that the content will drive the actual width. When scrollable is activated, it requires a column width to align headers. There would nowadays be ways to even handle dynamic width columns with scrollable.

Question is what the best fix would be. 
a) Set a default width for the column (as it is used "scrollable" in most cases), 
b) Handle the table headers differently: Use JavaScript to adjust the header column width to the content column width whenever content is rendered and columns with dynamic width exist
c) When scrollable is enabled, treat 0 width with a default value, i.e. 100px

Anyone any thoughts?

**Comment by apixandru** [comment]
i think that a default width would be better than treating 0 as an arbitrary value in a specific case
