### ISSUE TITLE
LazyTooltip

### ISSUE THREAD

**Issue by lippisch** [xwic/jWic#43]
When the LazyTooltip opens at the bottom of the page, it is displayed above the hover-element instead of below. As the position is calculated from the hover-element bottom, the tooltip floats over the element instead of above it. Even worse: If the mouse-cursor is in the tool-tip, it immediately closes the tooltip as the element below receives a mouseOut event.

**Comment by vzhovtyuk** [comment]
I was able to reproduce issue with tooltip at the bottom of the page ![lazytooltipbottompage](https://cloud.githubusercontent.com/assets/8643495/13112623/d6e1ee9c-d58b-11e5-8adf-15bc5a7f9df9.jpg)
There is no much place to put tooltip on the botton. But we can put tooltip under hover-element.
Please see proposed solution on screenshots.
Tooltip was moved to 30px botton:

![lazytooltipbottompagefixed](https://cloud.githubusercontent.com/assets/8643495/13112746/796cac88-d58c-11e5-9c04-1cf32f08cb3c.jpg)

Tooltip moved to bottom multi line size:
![lazytooltipbottompagefixedmultiline](https://cloud.githubusercontent.com/assets/8643495/13112625/d6e46d16-d58b-11e5-8557-0c62a310f4c9.jpg).

Issue with hiding tooltip with overlapping events was fixed as well.
Fixed in branch vitaliy_lazy_tooltip_issues
